server:
  port: 8080

spring:
  application:
    name: wanted

  datasource:
#    url: jdbc:mysql://${DATASOURCE_HOST}:3306/${MYSQL_DATABASE}
#    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    url: jdbc:mysql://${DATASOURCE_HOST}:3306/${MYSQL_DATABASE}


    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
#      ddl-auto: create-drop
#      ddl-auto: update
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      continue-on-error: true
#      data-locations: data.sql

jwt:
  secret-key: ${JWT_KEY}
  token:
    expired-time-ms: ${EXPIRATION_TIME}

#INSERT INTO employment (company_id, user_id, employment_title, employment_con, deadline, recommender_reward, applicant_reward)
#VALUES
#(1, 4, '더미 채용 제목 7', '더미 채용 내용 7', '2023-12-31', 1000, 500),
#(2, 4, '더미 채용 제목 8', '더미 채용 내용 8', '2023-12-31', 800, 400),
#(3, 4, '더미 채용 제목 9', '더미 채용 내용 9', '2023-12-31', 1200, 600);

